name: Backup on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p /home/runner/.ssh
        echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/id_ed25519
        chmod 600 /home/runner/.ssh/id_ed25519
        ssh-keyscan 192.168.1.195 > /home/runner/.ssh/known_hosts 2>&1
      shell: /usr/bin/bash -e {0}
    
    

    - name: Sync files
      run: rsync -avz --exclude '.git' ./ tiozzo@192.168.1.195:/home/tiozzo/Portfolio/
